/*
 * (c) 2025  ttelcl / ttelcl
 */

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using LcLauncher.ShellApps;
using LcLauncher.WpfUtilities;

namespace LcLauncher.Main.AppPicker;

public class AppViewModel: ViewModelBase
{
  public AppViewModel(
    ShellAppDescriptor descriptor)
  {
    Descriptor = descriptor;
  }

  public ShellAppDescriptor Descriptor { get; }

  public string Label => Descriptor.Label;

  public bool HasFile => Descriptor.HasFile;

  public string? FilePath  => Descriptor.HasFile ? Descriptor.FileSystemPath : null; 

  public bool HasFolder => Descriptor.HasFolder;

  public string? FolderPath => Descriptor.HasFolder ? Descriptor.FileSystemPath : null;

  public bool SupportsRawTile => Descriptor.IsExe;

  public bool SupportsDocTile => Descriptor.IsExe || Descriptor.IsDoc;

  public bool SupportsUriTile => Descriptor.IsUri;

  public bool SupportsAppTile => true; // for now: always true, but may be refined in future

  public AppCategory Category =>
    Descriptor.Kind switch {
      ShellAppKind.PlainFileApp =>
        SupportsRawTile 
        ? AppCategory.ExecutableApp
        : SupportsDocTile 
          ? AppCategory.DocumentApp
          : AppCategory.OtherApp,
      ShellAppKind.FolderFileApp =>
        SupportsRawTile
        ? AppCategory.ExecutableApp
        : SupportsDocTile
          ? AppCategory.DocumentApp
          : AppCategory.OtherApp,
      ShellAppKind.PlainFolderApp =>
        HasFolder ? AppCategory.FolderApp : AppCategory.OtherApp,
      ShellAppKind.Autogenerated =>
        AppCategory.ShortcutApp,
      ShellAppKind.AppId =>
        AppCategory.ModernApp,
      ShellAppKind.UriKind =>
        AppCategory.ProtocolApp,
      ShellAppKind.DottedName =>
        AppCategory.ClassicApp,
      _ => AppCategory.OtherApp,
    };

}
